- name: Deploy web App
  hosts: "all"
  vars_files: 
    - ansible_input_variables.yml  
  become: true
  tasks:
    # - name: Include encrypted file
    #   include_vars:
    #     file: aws_credentials.yml
          
    - name: Install nginx server on Ubuntu Server
      apt:
        name: nginx
        update_cache: true
   
    - name: Ensure directories for project files and configs
      file:
        name: "{{item}}"
        state: directory
        mode: "777"
      loop:
        - "/etc/nginx/conf.d"
        - "{{project_destination_repo}}"
    
    - name: Clone project repo in server
      git:
        repo: "{{project_git_repo}}"
        dest: "{{project_destination_repo}}"

    - name: Create server configs
      template:
        src: virtualhost.j2
        dest: "/etc/nginx/conf.d/project_site_{{ansible_host}}.conf"
    
    - name: Start nginx server
      service:
        name: nginx
        state: restarted

      






